# Generated by Django 5.1 on 2025-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
